import type { Metadata } from 'next'
import { Poppins } from "next/font/google"
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Source = Poppins({subsets: ["latin"], weight: [ "300", "400", "500", "700",'800']})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (   
    <html lang="en">
      <body  className={Source.className} >{children}</body>
    </html>
  )
}
